### ISSUE TITLE
Not recognising date style identifiers

### ISSUE THREAD

**Issue by ThubLives** [Flexget/Flexget#1393]
### Expected behaviour:
Recognise ISO-like dates in the format "2016.10.21".

### Actual behaviour:
Rejects all shows with date ID's.

### Steps to reproduce:
- Step 1: flexget execute --tasks <taskwithdateids>

#### Config:
```
  dailyshow_udlr:
    rss: <private_rss_feed>
    series:
      - The Daily Show:
          alternate_name: The Daily Show with Trevor Noah
          identified_by: date
```
  
#### Log:
```
2016-09-06 22:01 VERBOSE  parser_internal dailyshow_udlr Title `The.Daily.Show.with.Trevor.Noah.2016.08.18.Emily.King.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee` looks like series `The Daily Show` but cannot find a(n) `date` style identifier.
2016-09-06 22:01 VERBOSE  parser_internal dailyshow_udlr Title `The.Daily.Show.with.Trevor.Noah.2016.08.17.LeBron.James.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee` looks like series `The Daily Show` but cannot find a(n) `date` style identifier.
2016-09-06 22:01 VERBOSE  parser_internal dailyshow_udlr Title `The.Daily.Show.with.Trevor.Noah.2016.08.17.LeBron.James.1080p.CC.WEBRip.AAC2.0.x264-monkee` looks like series `The Daily Show` but cannot find a(n) `date` style identifier.
2016-09-06 22:01 VERBOSE  parser_internal dailyshow_udlr Title `The.Daily.Show.with.Trevor.Noah.2016.08.16.Yaa.Gyasi.and.Sharlto.Copley.1080p.CC.WEBRip.AAC2.0.x264-monkee` looks like series `The Daily Show` but cannot find a(n) `date` style identifier.
```

### Additional information:

- Flexget Version: 2.3.18
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Fedora 24

**Comment by liiight** [comment]
Did you try `date_yearfirst` option? 
http://flexget.com/Plugins/series/identified_by

**Comment by ThubLives** [comment]
I did not, but I just now tried changing the line to:
```
          identified_by: date_yearfirst
```
but it doesn't validate the config, giving me this:
```
Must be one of the following: ep, date, sequence, id, auto
```
I tried updating with pip, but it seems I've already got the latest.  I should probably clarify that the date auto-detection had been working for years against the same date format, without a need to specify the ID type in any way.

**Comment by gazpachoking** [comment]
Those options go alongside the identified_by one, like:
```yaml
identified_by: date
date_yearfirst: yes
```

**Comment by ThubLives** [comment]
Oh I see, thanks!  It's cool with those as separate config options.
No dice though.  I'm getting the same results when I execute the task.

**Comment by cvium** [comment]
Works for me.

**Comment by ThubLives** [comment]
Strange.  I'm still getting a huge pile of messages like in the log snippet above, but somehow this one show got recognised and downloaded, thus I'm getting this message as normal:
```
2016-09-13 19:31 VERBOSE  task          dailyshow_udlr REJECTED: `The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee` by seen plugin because entry with title `The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee` is already marked seen in the task dailyshow_udlr at 2016-09-13 06:43
```

**Comment by tarzasai** [comment]
Looks good to me:
```
  ut6:
    manual: yes
    template:
      - no_global
      - noseen
      - nofail
    series:
      - The Daily Show:
          alternate_name: The Daily Show with Trevor Noah
          identified_by: date
          date_yearfirst: yes
    mock:
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
```
output:
```
> flexget -L verbose execute --no-cache --task ut6 --dump eval
2016-09-25 10:29 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-09-25 10:29 VERBOSE  details       ut6             Produced 1 entries.
2016-09-25 10:29 VERBOSE  task          ut6             ACCEPTED: `The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee` by series plugin because choosing best available quality
2016-09-25 10:29 VERBOSE  details       ut6             Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2016-09-25 10:29 WARNING  task          ut6             Task doesn't have any output plugins, you should add (at least) one!
-- Accepted: ---------------------------
title            : The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee
url              : mock://localhost/mock/1703142312
original_url     : mock://localhost/mock/1703142312
accepted_by      : series
proper           : False
proper_count     : 0
quality          : 1080p webrip h264 aac
reason           : choosing best available quality
release_group    : None
series_date      : 2016-09-12 00:00:00
series_episodes  : 1
series_id        : 2016-09-12
series_id_type   : date
series_name      : The Daily Show
series_parser    : <SeriesParser(data=The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee,name=The Daily Show,id=2016-09-12 00:00:00,season=None,episode=None,quality=1080p webrip h264 aac,proper=0,status=OK)>
series_releases  : [47598]
series_season    : 2016
task             : ut6
```
I think we can we close this.

**Comment by cvium** [comment]
Unable to replicate. Closing. If you find a way to replicate it with a _fresh_ database, then feel free to reopen.

**Comment by ThubLives** [comment]
Updated with pip.  That specific example works now, but 90% do not.  Tried with a new database and minimal config.

[config-censored.yml.txt](https://
[censored.log.txt](https://github.com/Flexget/Flexget/files/492109/censored.log.txt)
github.com/Flexget/Flexget/files/492108/config-censored.yml.txt)

**Comment by ThubLives** [comment]
Here is the log.
[censored.log.txt](https://github.com/Flexget/Flexget/files/492110/censored.log.txt)

**Comment by liiight** [comment]
What if you name your show `The.Daily.Show.with.Trevor.Noah`?

**Comment by ThubLives** [comment]
I removed the `alternate_name` line and tried both `The Daily Show with Trevor Noah` and `The.Daily.Show.with.Trevor.Noah`, but I get the same 9 accepted and 91 undecided as with simply `The Daily Show`.

**Comment by liiight** [comment]
Is there any chance you upload your db somewhere, like Dropbox?

**Comment by ThubLives** [comment]
Keeping in mind it's a fresh database every time?  Yes, I think so.

**Comment by cvium** [comment]
I don't think the database is interesting. It could be the feed or the number of entries.

**Comment by liiight** [comment]
Yeah, i missed the part that it's a new db... 
How will the number of entries matter?

**Comment by ThubLives** [comment]
If it helps, I can reproduce it without the actual feed.  Here's a sample of 3 that parse and 5 that don't.  Notably, these behave the same using the feed or with mock input:

```
    mock:
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.21.Wendy.Williams.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.20.Jada.Pinkett.Smith.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.19.Nick.Jonas.and.Ben.Schnetzer.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.15.Bill.Clinton.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.14.Hannah.Hart.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.12.Tip.T.I.Harris.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.08.Howard.Schultz.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
      - { title: 'The.Daily.Show.with.Trevor.Noah.2016.09.07.Ava.DuVernay.Extended.1080p.CC.WEBRip.AAC2.0.x264-monkee' }
```

**Comment by liiight** [comment]
can you run a `locale` command?

**Comment by cvium** [comment]
@ThubLives Still works for me.

**Comment by tarzasai** [comment]
Still works on my Windows 7 too, with all the latest titles. BTW my Flexget is 2.3.2

**Comment by ThubLives** [comment]
My Flexget is 2.3.34.  locale command:
```
LANG=en_CA_UTF-8
LC_
LC_
LC_
LC_
LC_
LC_
LC_
LC_
```

**Comment by gazpachoking** [comment]
What version of python-dateutil do you have? All of the latest mock entries are parsed and accepted properly on my testing.

**Comment by cvium** [comment]
python-dateutil 2.5.2 could be the issue judging by their github and for some reason our requirement is `python-dateutil>=2.5.2`. We should probably bump that to 2.5.3 where the bug was fixed.

**Comment by liiight** [comment]
Nice @gazpachoking :thumbsup:

**Comment by cvium** [comment]
@liiight he cheated. He's the one who originally made them aware of the bug (https://github.com/dateutil/dateutil/issues/233)

**Comment by liiight** [comment]
Ah, I actually remember that now. I take my compliment back cheater!

**Comment by ThubLives** [comment]
Okay, I've updated, but the problem remains.  Testing with a fresh database and minimal config with the eight entries above, I still get the same five marked Unknown.

FlexGet (2.3.36)
python-dateutil (2.5.3)

**Comment by ThubLives** [comment]
After some messing around with pip, it seems I had both python-dateutil 2.5.3 and 2.1 installed somehow.  I think I've got 2.5.2 legit now and Flexget is merrily downloading date-style episodes. :)

**Comment by liiight** [comment]
Good because our next suggestion would be for you to stop watching that show :wink:
