### ISSUE TITLE
logging crash

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1558]
Just got this error for some log output, its nothing serious, but just wanted to report it.

Python 3.5.2 + Flexget 2.8.1
```
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\colorclass\windows.py", line 275, in write
    print(segment, file=self._original_stream, end='')
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 67: character maps to <undefined>
Call stack:
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task_queue.py", line 48, in run
    self.current_task.execute()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task.py", line 72, in wrapper
    return func(self, *args, **kw)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task.py", line 646, in execute
    self._execute()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task.py", line 612, in _execute
    self.__run_task_phase(phase)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task.py", line 453, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\plugins\filter\quality.py", line 37, in on_task_filter
    entry.reject('%s does not match quality requirement %s' % (entry['quality'], reqs))
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\entry.py", line 152, in reject
    self.run_hooks('reject', reason=reason, **kwargs)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\entry.py", line 80, in run_hooks
    func(self, **kwargs)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\plugins\operate\verbose.py", line 34, in verbose_details
    task_log.verbose(msg)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\flexget\logger.py", line 127, in verbose
    self.log(VERBOSE, msg, *args, **kwargs)
```

**Comment by liiight** [comment]
does this happen after a cli action?

**Comment by Andy2244** [comment]
This happens while trying to do some `log.verbose()` output. Maybe this is because of the way i do log output?
```python
log.verbose('some: %s, stuff: %s' % (stuff1, stuff2))
```
paranoidi noted this should be:
```python
log.verbose('some: %s, stuff: %s', stuff1, stuff2)
```
Still not sure what the exact difference is for the variants?

**Comment by gazpachoking** [comment]
Is this from existing code, or a new plugin you are making? Are you sure stuff1 and stuff2 are text, and not bytes?

**Comment by Andy2244** [comment]
I think it was data from anidb, using the http-api which should return strings for text fields. If this should not happen, just close the bug and i will do a better reporting job next time and also safe the input data that caused the crash.

**Comment by liiight** [comment]
```logtalk
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\colorclass\windows.py", line 275, in write
    print(segment, file=self._original_stream, end='')
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 67: character maps to <undefined>
```
it looks like the cause of this exception has nothing to do with what you were testing, not sure how to replicate that...

**Comment by liiight** [comment]
I replicated this, quite easily:
```logtalk
--- Logging error ---
Traceback (most recent call last):
  File "C:\python35\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "C:\python35\lib\encodings\cp1255.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe9' in position 45: character maps to <undefined>
Call stack:
  File "C:\python35\lib\threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "C:\python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Flexget\flexget\task_queue.py", line 48, in run
    self.current_task.execute()
  File "C:\Flexget\flexget\task.py", line 72, in wrapper
    return func(self, *args, **kw)
  File "C:\Flexget\flexget\task.py", line 646, in execute
    self._execute()
  File "C:\Flexget\flexget\task.py", line 576, in _execute
    log.debug('executing %s' % self.name)
Message: 'executing Aranyélet_test'
```
while trying to replicate https://github.com/Flexget/Flexget/issues/1553 I got a bunch of those

**Comment by gazpachoking** [comment]
I'm guessing this is because the encoding of the terminal doesn't support the character. I think somehow we should make our console log output just replace that character with a ? or something when the users terminal can't handle printing the character.

**Comment by liiight** [comment]
That's what we do with `console()` isn't it?

**Comment by gazpachoking** [comment]
Yeah. I'm thinking actually maybe we could do something on these lines:
```
old_stdout = sys.stdout
sys.stdout = io.TextIOWrapper(old_stdout.buffer, encoding=old_stdout.encoding, errors='backslashreplace')
```
Which should solve the issue for both logging and regular prints. I'm not sure if that's the best way to change the 'errors' argument on sys.stdout, it didn't let me do `sys.stdout.errors = 'replace'` directly.

**Comment by liiight** [comment]
Where will that go, root of `terminal.py`?

**Comment by gazpachoking** [comment]
Maybe make a function in terminal.py to set it up (and put the windows color code thing in there too) then call it in __init__.py?

**Comment by liiight** [comment]
I added this to `terminal.py`:
```python
def terminal_stuff():
    # Enable terminal colors on windows.
    # pythonw (flexget-headless) does not have a sys.stdout, this command would crash in that case
    if sys.platform == 'win32' and sys.stdout:
        Windows.enable(auto_colors=True)

    if sys.stdout:
        old_stdout = sys.stdout
        sys.stdout = io.TextIOWrapper(old_stdout.buffer, encoding=old_stdout.encoding, errors='backslashreplace')
```
and called it via manager `initialize`. Still get the same error

**Comment by gazpachoking** [comment]
@liiight Does it happen before our logging gets set up? We need to do it before the logging handler grab sys.stdout

**Comment by gazpachoking** [comment]
Maybe we should just fix it in our logging handler rather than trying to fix all of sys.stdout

**Comment by liiight** [comment]
I think i added this after our logging actually, but isn't this fix supposedly handle console output as well? That's the bigger issue here imo, you get reports of unicode errors constantly with different cli actions.

**Comment by gazpachoking** [comment]
Our console function is already doing a fix like this though? It's just the logging that doesn't have it right?

**Comment by liiight** [comment]
Hmm, seems all the cli issues with unicode happen when piping terminal table stuff. So the answer is yes I guess, logger only

**Comment by liiight** [comment]
Still the same.
http://pastebin.com/F1gAms1m
This is the config I used to test it:
```yaml
series_Aranyélet:
  mock:
    - {title: Aranyélet.S01E01.720p.x264-FlexGet}
  series:
    - Aranyélet
```

**Comment by gazpachoking** [comment]
@liiight Hmm. I was reproducing, but can't after that change. I had to add that `•` in the name, because my code page already supported the `é`
```
C:\Users\Chase\projects\flexget>py3\Scripts\flexget.exe --debug exec --tasks test_Aranyélet•
2016-12-25 11:25 DEBUG    manager                       Figuring out config load paths
2016-12-25 11:25 DEBUG    manager                       Found config: C:\Users\Chase\projects\flexget\config.yml
2016-12-25 11:25 DEBUG    manager                       Config file C:\Users\Chase\projects\flexget\config.yml selected
2016-12-25 11:25 DEBUG    manager                       sys.defaultencoding: utf-8
2016-12-25 11:25 DEBUG    manager                       sys.getfilesystemencoding: mbcs
2016-12-25 11:25 DEBUG    manager                       flexget detected io encoding: cp437
2016-12-25 11:25 DEBUG    manager                       os.path.supports_unicode_filenames: True
2016-12-25 11:25 DEBUG    plugin                        Trying to load plugins from: ['C:\\Users\\Chase\\projects\\flexget\\plugins', 'c:\\users\\chase\\projects\\flexget\\flexget\\plugins']
2016-12-25 11:25 DEBUG    safe                          Reading from cache file C:\Users\Chase\AppData\Local\Temp\safe-0.4.words.cache
2016-12-25 11:25 DEBUG    deluge                        Looking for deluge install in C:\Program Files (x86)\Deluge
2016-12-25 11:25 VERBOSE  deluge                        Cannot use deluge from install directory because its python version doesn't match.
2016-12-25 11:25 DEBUG    plugin                        ('Plugin `%s` requires `%s` to load.', 'memusage', 'ext lib `guppy`')
2016-12-25 11:25 DEBUG    plugin                        Plugins took 2.07 seconds to load. 266 plugins in registry.
2016-12-25 11:25 DEBUG    manager                       Connecting to: sqlite:///C:\\Users\\Chase\\projects\\flexget\\db-config.sqlite
2016-12-25 11:25 DEBUG    manager                       config_name: config
2016-12-25 11:25 DEBUG    manager                       config_base: C:\Users\Chase\projects\flexget
2016-12-25 11:25 DEBUG    manager                       New config data loaded.
2016-12-25 11:25 DEBUG    schema                        current flexget version already exist in db 2.8.12.dev
2016-12-25 11:25 DEBUG    parsing                       setting default movie parser to internal. (options: {'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x06E22630>, 'internal'
: <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x06E27EF0>})
2016-12-25 11:25 DEBUG    parsing                       setting default series parser to internal. (options: {'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x06E22630>, 'internal
': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x06E27EF0>})
2016-12-25 11:25 DEBUG    cron_env                      Encoding mbcs stored
2016-12-25 11:25 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'mbcs'
2016-12-25 11:25 DEBUG    task_queue                    task queue shutdown requested
2016-12-25 11:25 DEBUG    task          test_Aranyélet? executing test_Aranyélet?
2016-12-25 11:25 INFO     ipc.rpyc                      server started on [127.0.0.1]:55142
2016-12-25 11:25 DEBUG    disable       test_Aranyélet? Disabled built-in plugin(s): seen
2016-12-25 11:25 DEBUG    backlog       test_Aranyélet? 0 entries purged from backlog
2016-12-25 11:25 VERBOSE  details       test_Aranyélet? Produced 1 entries.
2016-12-25 11:25 DEBUG    parser_internal test_Aranyélet? Parsing series: `Aranyélet.S01E01.720p.x264-FlexGet` kwargs: {'name_regexps': [], 'sequence_regexps': [], 'name': 'Aranyélet', 'allow_groups': [], 'd
ate_dayfirst': None, 'date_regexps': [], 'date_yearfirst': None, 'id_regexps': [], 'special_ids': [], 'strict_name': False, 'prefer_specials': None, 'assume_special': None, 'identified_by': 'auto', 'ep_regex
ps': [], 'alternate_names': []}
2016-12-25 11:25 DEBUG    parser_internal test_Aranyélet? Parsing result: <SeriesParser(data=Aranyélet.S01E01.720p.x264-FlexGet,name=Aranyélet,id=None,season=1,episode=1,quality=720p h264,proper=0,status=OK)
> (in 5.988291947096343 ms)
2016-12-25 11:25 DEBUG    series        test_Aranyélet? Aranyélet.S01E01.720p.x264-FlexGet detected as <SeriesParser(data=Aranyélet.S01E01.720p.x264-FlexGet,name=Aranyélet,id=None,season=1,episode=1,quality=
720p h264,proper=0,status=OK)>, field: title
2016-12-25 11:25 DEBUG    series        test_Aranyélet? Aranyélet episode type totals: {'ep': 1}
2016-12-25 11:25 VERBOSE  series        test_Aranyélet? identified by is currently on `auto` for Aranyélet. Multiple id types may be accepted until it locks in on the appropriate type.
2016-12-25 11:25 DEBUG    series        test_Aranyélet? identified_by set to 'auto' based on series history
2016-12-25 11:25 DEBUG    series        test_Aranyélet? start with episodes: ['Aranyélet.S01E01.720p.x264-FlexGet']
2016-12-25 11:25 DEBUG    series        test_Aranyélet? current episodes: ['Aranyélet.S01E01.720p.x264-FlexGet']
2016-12-25 11:25 DEBUG    series        test_Aranyélet? -------------------- process_propers -->
2016-12-25 11:25 DEBUG    series        test_Aranyélet? propers - downloaded qualities: {<Quality(resolution=720p,source=unknown,codec=h264,audio=unknown)>: 0}
2016-12-25 11:25 VERBOSE  task          test_Aranyélet? REJECTED: `Aranyélet.S01E01.720p.x264-FlexGet` by series plugin because quality already downloaded
2016-12-25 11:25 DEBUG    urlrewriter   test_Aranyélet? Checking 0 entries
2016-12-25 11:25 VERBOSE  details       test_Aranyélet? Summary - Accepted: 0 (Rejected: 1 Undecided: 0 Failed: 0)
2016-12-25 11:25 WARNING  task          test_Aranyélet? Task doesn't have any output plugins, you should add (at least) one!
2016-12-25 11:25 DEBUG    series        test_Aranyélet? on_task_learn
2016-12-25 11:25 DEBUG    disable       test_Aranyélet? Re-enabled builtin plugin(s): seen
2016-12-25 11:25 DEBUG    util.simple_persistence test_Aranyélet? Flushing simple persistence for task test_Aranyélet? to db.
2016-12-25 11:25 DEBUG    task_queue                    task queue shut down
2016-12-25 11:25 INFO     ipc.rpyc                      listener closed
2016-12-25 11:25 INFO     ipc.rpyc                      server has terminated
2016-12-25 11:25 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-12-25 11:25 DEBUG    manager                       Shutting down
2016-12-25 11:25 DEBUG    manager                       Removed C:\Users\Chase\projects\flexget\.config-lock
```

**Comment by liiight** [comment]
Maybe you can force set that cp1255 encoder I use. Although I don't understand why that should matter...

**Comment by gazpachoking** [comment]
I tried code page 1255 as well, the accented e gets replaced with ? and it supports the bullet point char I was using funnily enough.

**Comment by gazpachoking** [comment]
Does that new debug line I added about io encoding come out properly to cp1255 for you?

**Comment by liiight** [comment]
Weird. Maybe I fucked up the test somehow, I'll retest tomorrow.

**Comment by Andy2244** [comment]
Still getting this error in my anidb_feed plugin, while trying to handle japanese group names.

The test string can be constructed via:
```python
text = '&amp;#x30FD;&amp;acute;&amp;#x30FC;`&amp;#x30CE;'
a = html.unescape(text)
c = BeautifulSoup(a, "html5lib").text

>> ヽ´ー`ノ
```

```
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u30fd' in position 80: character maps to <undefined>
Call stack:
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\users\andy\appdata\local\programs\python\python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\andy\documents\github\flexget\flexget\task_queue.py", line 48, in run
    self.current_task.execute()
  File "c:\users\andy\documents\github\flexget\flexget\task.py", line 72, in wrapper
    return func(self, *args, **kw)
  File "c:\users\andy\documents\github\flexget\flexget\task.py", line 646, in execute
    self._execute()
  File "c:\users\andy\documents\github\flexget\flexget\task.py", line 612, in _execute
    self.__run_task_phase(phase)
  File "c:\users\andy\documents\github\flexget\flexget\task.py", line 453, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "c:\users\andy\documents\github\flexget\flexget\task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "c:\users\andy\documents\github\flexget\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\andy\documents\github\flexget\flexget\plugins\filter\accept_all.py", line 26, in on_task_filter
    entry.accept()
  File "c:\users\andy\documents\github\flexget\flexget\entry.py", line 139, in accept
    self.run_hooks('accept', reason=reason, **kwargs)
  File "c:\users\andy\documents\github\flexget\flexget\entry.py", line 80, in run_hooks
    func(self, **kwargs)
  File "c:\users\andy\documents\github\flexget\flexget\plugins\operate\verbose.py", line 34, in verbose_details
    task_log.verbose(msg)
  File "c:\users\andy\documents\github\flexget\flexget\logger.py", line 129, in verbose
    self.log(VERBOSE, msg, *args, **kwargs)
Message: 'ACCEPTED: `Drifters 12 [\u30fd´\u30fc`\u30ce] [720p]` by accept_all plugin'
Arguments: ()
2017-01-06 16:11 VERBOSE  task          anidb-feed      ACCEPTED: `Drifters 12 [?´?`?] [720p]` by accept_all plugin
```

**Comment by Andy2244** [comment]
I just had to switch back to python 2.7 from 3.5, since i got too many python 2.7 related bugs. Now i noticed that i do not get the above exception, so this seems python 3+ related.
