### ISSUE TITLE
Series flagged invalid

### ISSUE THREAD

**Issue by jonashrem** [Flexget/Flexget#735]
I got an error on a task with many items (2000) after switching the parser to guesit

>2015-12-21 02:35 CRITICAL task         foo BUG: Unhandled error in plugin >metainfo_series: Series flagged invalid
>Traceback (most recent call last):
> File "/home/stuff/flexget-trunk/flexget/task.py", line 438, in __run_plugin
>    return method(*args, **kwargs)
>  File "/home/stuff/flexget-trunk/flexget/event.py", line 22, in __call__
>   return self.func(*args, **kwargs)
>  File "/home/stuff/flexget-trunk/flexget/plugins/metainfo/series.py", line 31, in on_task_metainfo
>    self.guess_entry(entry)
>  File "/home/stuff/flexget-trunk/flexget/plugins/metainfo/series.py", line 46, in guess_entry
>    populate_entry_fields(entry, parsed, config)
>  File "/home/stuff/flexget-trunk/flexget/plugins/filter/series.py", line 723, in populate_entry_fields
>    entry['series_id'] = parser.pack_identifier
>  File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 548, in pack_identifier
>    return self.identifier
>  File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 539, in identifier
>    return self.identifiers[0]
>  File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 524, in identifiers
>    raise Exception('Series flagged invalid')
>Exception: Series flagged invalid

after tasks run for about the hours. Any idea what is causing this (other tasks with viewer entries work fine)?

Need any extra infos?

Flexget version: 1.2.413.dev

sniped from config file (other task only have another file)

>  foo:
>    interval: 7 days
>    parsing:
>      movie: guessit
>      series: guessit
>
>    #manual: yes
>    seen: global
>    rss:/localpath/foo.rss
>    set:
>      content-disposition: no
>      filename: "{{ series_name }}-{{ series_id }}-[{{ quality|upper }}].torrent"
>    download:
>      path: /var/torrenttmp/
>    metainfo_series: yes
>    thetvdb_lookup: yes

**Comment by liiight** [comment]
Did you try with recent guessit version?

**Comment by jonashrem** [comment]
Seems to be GuessIt 2.0.3 but as I auto update flexget on weekly base it might have been an older version on 21th december. 

Shall I test again with current version?

**Comment by liiight** [comment]
why not

**Comment by jonashrem** [comment]
now I get a different error

`Traceback (most recent call last):
  File "/home/stuff/flexget-trunk/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/stuff/flexget-trunk/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/stuff/flexget-trunk/flexget/plugins/filter/series.py", line 1109, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/home/stuff/flexget-trunk/flexget/plugins/filter/series.py", line 1225, in parse_series
    parsed = get_plugin_by_name('parsing').instance.parse_series(entry['title'], name=series_name, **params)
  File "/home/stuff/flexget-trunk/flexget/plugins/parsers/plugin_parsing.py", line 70, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_guessit.py", line 315, in parse_series
    guess_result = guessit_api.guessit(data, options=guessit_options)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/guessit/api.py", line 76, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rebulk.py", line 275, in matches
    self._execute_rules(matches, context)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rebulk.py", line 306, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/processors.py", line 56, in when
    conflicting_matches = matches.conflicting(match)
  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/match.py", line 388, in conflicting
    ret.remove(match)
ValueError: list.remove(x): x not in list
`

**Comment by liiight** [comment]
@tolial what do you think

**Comment by Toilal** [comment]
It would help to have the value of `data` at 

```
File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_guessit.py", line 315, in parse_series
guess_result = guessit_api.guessit(data, options=guessit_options)
```

Maybe you could edit the file to add a `print data` statement just before this line ?

It's definitively a guessit issue.

**Comment by Toilal** [comment]
That beeing said, i'll add a global try/except in guessit to display the failing file when an unexpected exception occurs.

**Comment by Toilal** [comment]
Please upgrade to guessit 2.0.4 i've just released, i'll give more information to solve the issue !

**Comment by jonashrem** [comment]
the last data entry before crash is

`[HorribleSubs] Prince of Stride - Alternative - 05 [1080p].mkv`

before that several entries seem to pass without error

**Comment by jonashrem** [comment]
```
Traceback (most recent call last):
  File "/home/stuff/flexget-trunk/flexget/plugin.py", line 381, in _load_plugins_from_dirs
    __import__(module_name)
  File "/home/stuff/flexget-trunk/flexget/plugins/output/send_telegram.py", line 9, in <module>
    from telegram.error import TelegramError
ImportError: No module named telegram.error

```

I thing latest git push update crashed something

**Comment by liiight** [comment]
Shit. That is completely unrelated to your bug, but thanks anyway

**Comment by jonashrem** [comment]
```
2016-02-03 01:12 CRITICAL task          HorribleSubs (CR) complete BUG: Unhandled error in plugin series: An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=2.0.4\nstring=[HorribleSubs] Prince of Stride - Alternative - 05 [1080p].mkv\noptions={u'allowed_languages': [u'en', u'fr'], u'name_only': True, 'strict_name': True, u'episode_prefer_number': True, 'alternate_names': [u'Triage X', u'\u30c8\u30ea\u30a2\u30fc\u30b8X'], u'sequence_regexps': [], u'date_regexps': [], 'assume_special': None, 'prefer_specials': True, 'allow_groups': [], u'date_day_first': None, 'identified_by': u'id', 'name': u'Triage X', u'allowed_countries': [u'us', u'uk', u'gb'], 'special_ids': [u'OAV', u'OVA', u'OAD', u'Special', u'Extra', u'.5'], u'date_year_first': None, 'date_dayfirst': None, 'date_yearfirst': None, 'name_regexps': [], u'id_regexps': [u'(\\d\\d)-(\\d\\d)', u'(\\d\\d)*', u'(\\d*)', u'(\\d+) bluray', u'(Batch)', u'Vol(\\d*)-(\\d*)', u'Vol.(\\d\\d)', u'Vol.(\\d)', u'Vol.(\\d\\d\\d)', u'\\b(?:M{0,3})(?:D?C{0,3}|C[DM])(?:L?X{0,3}|X[LC])(?:V?I{0,3}|I[VX])(?=(\\.\\s|\\s|\\)|$))'], u'ep_regexps': [], u'type': u'episode'}\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/guessit/api.py", line 102, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rebulk.py", line 275, in matches\n    self._execute_rules(matches, context)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rebulk.py", line 306, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rules.py", line 318, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/rules.py", line 339, in execute_rule\n    when_response = rule.when(matches, context)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/processors.py", line 56, in when\n    conflicting_matches = matches.conflicting(match)\n  File "/home/stuff/flexget-trunk/local/lib/python2.7/site-packages/rebulk/match.py", line 388, in conflicting\n    ret.remove(match)\nValueError: list.remove(x): x not in list\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================
2016-02-03 01:12 CRITICAL manager       HorribleSubs (CR) complete An unexpected crash has occurred. Writing crash report to /home/jonas/.flexget/crash_report.2016.02.03.011220932317.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.446.dev

```

here the output of new version

**Comment by Toilal** [comment]
I can reproduce using a standalone script, i've created an issue in guessit bugtracker. I'll try to fix is as soon as possible.

https://github.com/guessit-io/guessit/issues/267

**Comment by Toilal** [comment]
Problem is that some id regexp may return empty matches. I'll fix rebulk, the libray handling patterns behind guessit, to filter out those empty matches. It should fix the issue.

**Comment by liiight** [comment]
Is this still relevant?

**Comment by jonashrem** [comment]
I started a new test. Can tell you more in a few minutes.

**Comment by jonashrem** [comment]
unfortunatly still happening. 

This error came up (after running for over 5 hours which is quite a lot longer compared to builtin parser)
> 2016-04-05 03:58 VERBOSE  series        HorribleSubs (CR) complete Found different quality for [HorribleSubs] DD Hokuto no Ken 2 - Ichigo Aji+ - 12 [1080p].mkv. Was 1080p, overriding with 1080p dd5.1.
> 2016-04-05 03:58 CRITICAL task          HorribleSubs (CR) complete BUG: Unhandled error in plugin metainfo_series: Series flagged invalid
> Traceback (most recent call last):
>   File "/home/stuff/flexget-trunk/flexget/task.py", line 438, in __run_plugin
>     return method(*args, **kwargs)
>   File "/home/stuff/flexget-trunk/flexget/event.py", line 22, in __call__
>     return self.func(*args, **kwargs)
>   File "/home/stuff/flexget-trunk/flexget/plugins/metainfo/series.py", line 31, in on_task_metainfo
>     self.guess_entry(entry)
>   File "/home/stuff/flexget-trunk/flexget/plugins/metainfo/series.py", line 46, in guess_entry
>     populate_entry_fields(entry, parsed, config)
>   File "/home/stuff/flexget-trunk/flexget/plugins/filter/series.py", line 870, in populate_entry_fields
>     entry['series_id'] = parser.pack_identifier
>   File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 548, in pack_identifier
>     return self.identifier
>   File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 539, in identifier
>     return self.identifiers[0]
>   File "/home/stuff/flexget-trunk/flexget/plugins/parsers/parser_common.py", line 524, in identifiers
>     raise Exception('Series flagged invalid')
> Exception: Series flagged invalid

**Comment by jonashrem** [comment]
was tested with 1.2.500.dev

**Comment by cvium** [comment]
Unable to reproduce. Please upgrade to latest guessit and rebulk. Closing.
