### ISSUE TITLE
Can't clear movie-queue

### ISSUE THREAD

**Issue by rhomat27** [Flexget/Flexget#857]
Hi, 

When I try to clear the movie-queue I get errors in Python and it doesn't clear the queue. I've tried several times.

`matt@SYS:~/data$ flexget movie-queue clear
Removing the following movies from movie queue:
-------------------------------------------------------------------------------
None
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==1.2.448', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 300, in start
    self.handle_cli()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 327, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_queue.py", line 29, in do_cli
    clear()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_queue.py", line 120, in clear
    queue_del(title=item.title)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/movie_queue.py", line 354, in queue_del
    (title, imdb_id, tmdb_id, movie_id))
flexget.plugins.filter.movie_queue.QueueError
`

**Comment by liiight** [comment]
This was fixed and will be out next release

**Comment by liiight** [comment]
try again please, should be fixed

**Comment by liiight** [comment]
I'll take that as a yes :wink:

**Comment by rhomat27** [comment]
:) I haven't had a chance to test yet. It's pretty busy for me during the week. 

If I have any issue, I'll let you know at the weekend. 

Thanks!

**Comment by rhomat27** [comment]
Actually, this didn’t fix the issue. I have some weird entries in the movie queue listed as “None.” Might this be a problem? Now, there is a slight difference in the symptom. Previously, it would actually remove several movies and then stop about halfway through. Now, it’s stopping immediately.

matt@SYS:~$ flexget movie-queue clear
Removing the following movies from movie queue:
-------------------------------------------------------------------------------
None
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==1.2.451', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 300, in start
    self.handle_cli()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 327, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_queue.py", line 30, in do_cli
    clear(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_queue.py", line 121, in clear
    queue_del(title=item.title, queue_name=options.queue_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/movie_queue.py", line 369, in queue_del
    (title, imdb_id, tmdb_id, movie_id, queue_name))
flexget.plugins.filter.movie_queue.QueueError
matt@SYS:~$ flexget -V
1.2.451
You are on the latest release.


matt@SYS:~$ flexget movie-queue list
-------------------------------------------------------------------------------
IMDB id    TMDB id Title                                 Quality
-------------------------------------------------------------------------------
tt0285331  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1898069  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2193021  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0898266  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2741602  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2313114  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0904208  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0056751  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1462059  355426  Falling Skies                         h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0182576  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0944947  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1519931  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1699748  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1856010  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1797404  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt3205802  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2937900  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt0804503  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2364582  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1442437  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1870479  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt3012698  289314  Olive Kitteridge                      h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2372162  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt3006802  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1837576  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2647544  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1632701  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2356777  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt2306299  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1520211  None    None                                  h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1135084  22907   Takers                                h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt1608290  None    Zoolander 2 (2016)                    h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip
tt3499096  None    Race (2016)                           h264 720p !dvdrip !cam !workprint !ts !tc !r5 !preair !tvrip !dsr !sdtv !hr !hdrip

**Comment by liiight** [comment]
Is it possible you didn't restart a daemon?

**Comment by rhomat27** [comment]
I don’t run the daemon, I run it from cron.
